### ISSUE TITLE
Long integer literal crashes RedBaron

### ISSUE THREAD

**Issue by kayhayen** [Psycojoker/redbaron#38]
This is valid Python2 code, but not to RedBaron. It may not happen all the time, maybe just in this context.

3L

Traceback (most recent call last):
  File "./misc/autoformat.py", line 12, in <module>
    red = RedBaron(source_code.read().rstrip()+"\n")
  File "/usr/local/lib/python2.7/dist-packages/redbaron.py", line 2597, in __init__
    self.node_list = NodeList.from_fst(baron.parse(source_code), parent=self, on_attribute="root")
  File "/usr/local/lib/python2.7/dist-packages/redbaron.py", line 266, in from_fst
    return klass(map(lambda x: Node.from_fst(x, parent=parent, on_attribute=on_attribute), node_list), parent=parent, on_attribute=on_attribute)
  File "/usr/local/lib/python2.7/dist-packages/redbaron.py", line 266, in <lambda>
    return klass(map(lambda x: Node.from_fst(x, parent=parent, on_attribute=on_attribute), node_list), parent=parent, on_attribute=on_attribute)
  File "/usr/local/lib/python2.7/dist-packages/redbaron.py", line 437, in from_fst
    return globals()[class_name](node, parent=parent, on_attribute=on_attribute)
  File "/usr/local/lib/python2.7/dist-packages/redbaron.py", line 2163, in __init__
    self.value = int(self.value)
ValueError: invalid literal for int() with base 10: '3L'

**Comment by Psycojoker** [comment]
Fixed and released.

**Comment by ibizaman** [comment]
I know it's a closed bug but I still edited the source code to make it more readable.
Btw, @Psycojoker, could you add in the commit(s) that fixes this request a line like "fixes #38" or "refs #38" ? That way we have a link between the commit and the issue.
