### ISSUE TITLE
Cannot parse line continuations onto an empty line 

### ISSUE THREAD

**Issue by rmmh** [Psycojoker/redbaron#58]
Python accepts code like this:

    >>> 3\
    ... 
    3

But RedBaron does not:

	$ python -c 'import redbaron; redbaron.RedBaron("3\\")'
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "/home/rmmh/.local/lib/python2.7/site-packages/redbaron.py", line 2717, in __init__
	    self.node_list = NodeList.from_fst(baron.parse(source_code), parent=self, on_attribute="root")
	  File "/home/rmmh/.local/lib/python2.7/site-packages/baron/baron.py", line 51, in parse
	    tokens = tokenize(source_code, False)
	  File "/home/rmmh/.local/lib/python2.7/site-packages/baron/baron.py", line 72, in tokenize
	    return mark_indentation(inner_group(space_group(_tokenize(group(split(pouet)), print_function))))
	  File "/home/rmmh/.local/lib/python2.7/site-packages/baron/inner_formatting_grouper.py", line 112, in group
	    return list(group_generator(sequence))
	  File "/home/rmmh/.local/lib/python2.7/site-packages/baron/inner_formatting_grouper.py", line 189, in group_generator
	    raise UnExpectedFormattingToken(debug_text)
	baron.inner_formatting_grouper.UnExpectedFormattingToken: Unexpected 'space' token:

	   1 3\
	   2 <--- here

	Should have been grouped on either ('INT', '3') (before) or ('ENDMARKER', '') (after) token.

**Comment by rmmh** [comment]
woops, should have filed this against Baron. Refiled as baron#65
